spring:
  datasource:
    url: jdbc:h2:tcp://localhost/e:/Study/Project/BGetToKnow/BGetToKnow
    username: j-kyu
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
server:
  port: 80

