spring:
  datasource:
    url: jdbc:h2:tcp://localhost/e:/Study/Project/BGetToKnow/BGetToKnow
    username: j-kyu
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #     show_sql: true
        format_sql: true